trigger:
- main   # branch to trigger pipeline

variables:
- group: gitops-variables   # contains your GitHub PAT as GITOPS_INFRA_PAT

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
      displayName: "Build Java App with Maven"

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(System.DefaultWorkingDirectory)/target'
        artifactName: 'drop'
      displayName: "Publish Build Artifacts"

    - task: Docker@2
      displayName: "Build and Push Docker Image"
      inputs:
        containerRegistry: "gitops-acr-conn"   # your ACR service connection
        repository: "java-gitops-app"
        command: "buildAndPush"
        Dockerfile: "Dockerfile"
        tags: |
          $(Build.BuildId)

    - script: |
        chmod +x trivy-scan.sh
        ./trivy-scan.sh
      displayName: "Run Trivy Scan"

    - script: |
        chmod +x zap-scan.sh
        ./zap-scan.sh
      displayName: "Run OWASP ZAP Scan"

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - script: |
        echo "Updating GitOps manifests in GitHub repo..."
        git config --global user.email "azure-pipelines@devops.com"
        git config --global user.name "Azure Pipelines"

        # Clone infra repo from GitHub using PAT
        git clone https://$(GITOPS_INFRA_PAT)@github.com/Poojass1998/gitops-infra.git

        cd gitops-infra

        # Update deployment.yaml with new Docker image tag
        sed -i "s|image: .*|image: gitopsacr12345.azurecr.io/java-gitops-app:$(Build.BuildId)|" k8s/deployment.yaml

        git add .
        git commit -m "Update image to build $(Build.BuildId)"
        git push origin main
      displayName: "Update GitOps repo with new image"

